#+TITLE: raspberrypi_setup
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Repository Information
  - Author :: Peter Polidoro
  - License :: BSD

* Raspberry Pi Setup

** Setup Ubuntu Server SD Card

   On a host computer run:

   #+BEGIN_SRC sh
     cd ~/Downloads
     wget https://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz
   #+END_SRC

   Plug SD card into host computer and run:

   #+BEGIN_SRC sh
     lsblk -p
   #+END_SRC

   After verifying which device is your SD card (e.g. /dev/sdb1), unmount it
   using the following command:

   #+BEGIN_SRC sh
     umount /dev/sdb1
   #+END_SRC

   Next, we can write the image file to the SD card (be very careful using dd!):
   - if= path to your image
   - of = where to write output (note: do not include partition number)

     Wait for a long time for command to finish.

     #+BEGIN_SRC sh
       cd ~/Downloads
       xzcat ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz | sudo dd of=/dev/sdb bs=4M status=progress conv=fsync
       sudo touch $(findmnt -S /dev/sdb1 -o TARGET -n)/ssh
       umount /dev/sdb1
       umount /dev/sdb2
     #+END_SRC

     Remove SD card from host computer.

** Initialize Raspberry Pi

   Insert the SD card you’ve set up with Ubuntu Server into the microSD card slot on
   the underside of your Raspberry Pi.

   Use an Ethernet cable to connect the Ethernet port on Raspberry Pi to an
   Ethernet socket on the wall, or toon your internet router, or to a host
   computer ethernet port, or to a usb to ethernet adapter.

   Plug the USB power supply into a socket and connect it to your Raspberry Pi’s
   power port.

*** SSH into Raspberry Pi

    #+BEGIN_SRC sh
      ssh ubuntu@ubuntu
    #+END_SRC

**** If 'No route to host' error:

     #+BEGIN_SRC sh
       ip addr
       # find ip addresses of various ip links on the host computer
       # e.g. 192.168.1.117
       nmap -p22 --open -sV 192.168.1.0/24
       ssh ubuntu@192.168.1.77
       # e.g. 10.42.0.1
       nmap -p22 --open -sV 10.42.0.0/24
       ssh ubuntu@10.42.0.192
     #+END_SRC

*** Update

    #+BEGIN_SRC sh
      sudo apt update
      sudo apt full-upgrade
      # may need to reboot before upgrade if unattended-upgr has cache lock
    #+END_SRC

*** Setup DHCP for USB Ethernet Adapter Peer to Peer Connection

    #+BEGIN_SRC sh
      sudo apt install isc-dhcp-server -y
      sudo wget -O /etc/dhcp/dhcpd.conf https://raw.githubusercontent.com/janelia-experimental-technology/raspberrypi_setup/master/etc/dhcp/dhcpd.conf
      sudo wget -O /etc/default/isc-dhcp-server https://raw.githubusercontent.com/janelia-experimental-technology/raspberrypi_setup/master/etc/default/isc-dhcp-server
      sudo systemctl restart isc-dhcp-server
    #+END_SRC

*** Setup udev rules for Teensy Connection

    #+BEGIN_SRC sh
      sudo wget -P /etc/udev/rules.d/ https://raw.githubusercontent.com/janelia-experimental-technology/raspberrypi_setup/master/etc/udev/rules.d/49-teensy.rules
    #+END_SRC

*** Install Docker

    [[https://github.com/janelia-experimental-technology/docker_setup/blob/master/DOCKER_SETUP_LINUX.org]]
